sudo: required
services:
  - docker

before_install:
  - docker-compose up --build -d


script:
  - docker-compose exec api python3 manage.py -m unittest test

after_success:
  - docker build -t texplode/api  ./
  - docker build -t texplode/nginx  ./nginx
  - docker build -t texplode/smtp  ./docker-smtp


# Login to Docker 
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# # Take images and push them to dockerhub

#   - docker push texplode/api
#   - docker push texplode/nginx
#   - docker push texplode/docker-smtp



# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: mulit-docker
#   env: MulitDocker-env
#   bucket_name: elasticbeanstalk-us-east-2-632874205370
#   bucket_path: docker-react
#   on:
#     branch: master

#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"