# Generated by Django 2.2.4 on 2019-08-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaccount',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='started_date',
            field=models.DateTimeField(),
        ),
    ]
