# Generated by Django 2.2.4 on 2019-08-17 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20190817_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 19, 18, 47, 879893)),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 19, 18, 47, 879856)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 19, 18, 47, 881079)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='started_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 19, 18, 47, 881047)),
        ),
    ]
