# Generated by Django 2.2.4 on 2019-08-17 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_auto_20190817_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberaccount',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 20, 51, 616986)),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 20, 51, 616950)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 20, 51, 618188)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='started_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 20, 51, 618154)),
        ),
    ]
