# Generated by Django 2.2.4 on 2019-08-17 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_auto_20190817_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='member_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 34, 11, 722022)),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 34, 11, 721986)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 34, 11, 724034)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='started_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 34, 11, 723996)),
        ),
    ]
