# Generated by Django 2.2.4 on 2019-08-18 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_auto_20190817_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 15, 46, 59, 690294)),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 15, 46, 59, 690259)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 15, 46, 59, 692130)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='started_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 15, 46, 59, 692092)),
        ),
    ]
