# Generated by Django 2.2.4 on 2019-08-25 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_auto_20190818_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 12, 39, 56, 343257)),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 12, 39, 56, 343222)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 12, 39, 56, 346078)),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='started_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 12, 39, 56, 346038)),
        ),
    ]
